id: AC43F6BF4
title: Prayer to Khandro Tsering Chödrön
type: translation
pechas:
- I7FEEA978
- IFBAEFE38
- IA6648626
- I2166500D
- I91FE2BB1
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:41.506204
  last_modified_at: 2023-01-04 12:48:41.506225
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I7FEEA978/2C61: 4A85
  IFBAEFE38/4417: 4A85
  IA6648626/3522: 4A85
  I2166500D/4204: 4A85
  I91FE2BB1/8483: 4A85
